LangString addOrReinstall ${LANG_ENGLISH} "Add/Reinstall components"
LangString alreadyInstalled ${LANG_ENGLISH} "Already installed"
LangString alreadyInstalledLong ${LANG_ENGLISH} "${PRODUCTNAME} ${VERSION} is already installed. Select the action you want to perform and click Next to continue."
LangString appRunning ${LANG_ENGLISH} "${PRODUCTNAME} is running! Please close it and try again."
LangString appRunningOkKill ${LANG_ENGLISH} "${PRODUCTNAME} is running!$\nClick OK to terminate it."
LangString chooseMaintenanceOption ${LANG_ENGLISH} "Choose a maintenance option."
LangString choowHowToInstall ${LANG_ENGLISH} "Choose how you want to install ${PRODUCTNAME}."
LangString createDesktop ${LANG_ENGLISH} "Create a desktop shortcut"
LangString dontUninstall ${LANG_ENGLISH} "Do not uninstall"
LangString dontUninstallDowngrade ${LANG_ENGLISH} "Do not uninstall (downgrades are disabled by this installer)"
LangString failedToKillApp ${LANG_ENGLISH} "Unable to terminate ${PRODUCTNAME}. Please close it and try again."
LangString installingWebview2 ${LANG_ENGLISH} "Installing WebView2..."
LangString newerVersionInstalled ${LANG_ENGLISH} "A newer version of ${PRODUCTNAME} is already installed! Installing an older version is not recommended. Select the action you want to perform and click Next to continue."
LangString older ${LANG_ENGLISH} "older"
LangString olderOrUnknownVersionInstalled ${LANG_ENGLISH} "An $R4 version of ${PRODUCTNAME} is already installed. It is recommended to uninstall the current version before installing. Select the action you want to perform and click Next to continue."
LangString silentDowngrades ${LANG_ENGLISH} "Downgrades are disabled on this installer and cannot be performed silently. Please use the GUI installer.$\n"
LangString unableToUninstall ${LANG_ENGLISH} "Unable to uninstall!"
LangString uninstallApp ${LANG_ENGLISH} "Uninstall ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ENGLISH} "Uninstall before installing"
LangString unknown ${LANG_ENGLISH} "unknown"
LangString webview2AbortError ${LANG_ENGLISH} "Unable to install WebView2! This app cannot run without it. Try restarting the installer."
LangString webview2DownloadError ${LANG_ENGLISH} "Error: Failed to download WebView2 - $0"
LangString webview2DownloadSuccess ${LANG_ENGLISH} "WebView2 bootstrapper downloaded successfully"
LangString webview2Downloading ${LANG_ENGLISH} "Downloading WebView2 bootstrapper..."
LangString webview2InstallError ${LANG_ENGLISH} "Error: Failed to install WebView2, error code: $1"
LangString webview2InstallSuccess ${LANG_ENGLISH} "WebView2 installed successfully"
LangString deleteAppData ${LANG_ENGLISH} "Delete application data"
LangString launchApp ${LANG_ENGLISH} "Launch ${PRODUCTNAME}"

LangString customWelcomeTitle ${LANG_ENGLISH} "Welcome"
LangString customWelcomeSubtitle ${LANG_ENGLISH} "Install ${PRODUCTNAME}"
LangString customWelcomeHeading ${LANG_ENGLISH} "Welcome to Atelier"
LangString customWelcomeVersion ${LANG_ENGLISH} "Version"
LangString customWelcomeBody ${LANG_ENGLISH} "Atelier is a local AI image generation studio with multi-model and multi-provider support.$\n$\nThe installer will detect and configure the WebView2 runtime automatically."
LangString customWelcomeHint ${LANG_ENGLISH} "Click Next to continue the setup wizard."
LangString customInfoTitle ${LANG_ENGLISH} "Before You Install"
LangString customInfoSubtitle ${LANG_ENGLISH} "Please review the following"
LangString customInfoBody ${LANG_ENGLISH} "This wizard will install ${PRODUCTNAME} to the directory you choose and create a Start Menu shortcut."
LangString customInfoFeature1 ${LANG_ENGLISH} "• Runs locally — your data stays on this machine"
LangString customInfoFeature2 ${LANG_ENGLISH} "• Supports OpenAI, Gemini, and other providers"
LangString customInfoFeature3 ${LANG_ENGLISH} "• Built with Tauri 2 — lightweight and fast"
LangString customInfoWebView2 ${LANG_ENGLISH} "If WebView2 is not installed, the installer will download and install it."
LangString customFinishTitle ${LANG_ENGLISH} "Installation Complete"
LangString customFinishText ${LANG_ENGLISH} "${PRODUCTNAME} has been successfully installed.$\n$\nYou can launch the app now or click Finish to exit the wizard."
