# Check / export the local toolchain for `tauri android init` / `tauri android dev`.
# Required: JDK 17, Android SDK + NDK, rustup android targets.
# Extra args are run in this process so ANDROID_* and TAURI_DEV_HOST persist:
#   powershell -File scripts/android-env.ps1 npx tauri android dev
param(
  [Parameter(ValueFromRemainingArguments = $true)]
  [string[]]$Passthru
)

$ErrorActionPreference = "Continue"

function Ok($msg) { Write-Host "[ok]  $msg" -ForegroundColor Green }
function Miss($msg) { Write-Host "[!!] $msg" -ForegroundColor Yellow }

$failed = $false

if ($env:JAVA_HOME -and (Test-Path $env:JAVA_HOME)) {
  Ok "JAVA_HOME=$env:JAVA_HOME"
} else {
  Miss "JAVA_HOME is not set. Install JDK 17 and set JAVA_HOME."
  $failed = $true
}

$sdkCandidates = @(
  $env:ANDROID_HOME,
  $env:ANDROID_SDK_ROOT,
  "D:\Android\Sdk",
  "$env:LOCALAPPDATA\Android\Sdk"
) | Where-Object { $_ }

$sdk = $sdkCandidates | Where-Object { $_ -and (Test-Path $_) } | Select-Object -First 1
if ($sdk) {
  $env:ANDROID_HOME = $sdk
  $env:ANDROID_SDK_ROOT = $sdk
  Ok "Android SDK=$sdk"
} else {
  Miss "Android SDK not found. Install Android Studio (SDK + NDK), then set ANDROID_HOME (and NDK_HOME if the NDK is not under the SDK)."
  $failed = $true
}

$ndk = $env:NDK_HOME
if (-not $ndk -and $sdk) {
  $ndkDir = Join-Path $sdk "ndk"
  if (Test-Path $ndkDir) {
    $ndk = Get-ChildItem $ndkDir -Directory | Sort-Object Name -Descending | Select-Object -First 1 -ExpandProperty FullName
  }
}
if ($ndk -and (Test-Path $ndk)) {
  $env:NDK_HOME = $ndk
  Ok "NDK=$ndk"
} else {
  Miss "NDK not found. In Android Studio SDK Manager install NDK (Side by side), then set NDK_HOME."
  $failed = $true
}

$need = @("aarch64-linux-android", "x86_64-linux-android")
$installed = rustup target list --installed 2>$null
foreach ($t in $need) {
  if ($installed -contains $t) {
    Ok "rustup target $t"
  } else {
    Miss "rustup target $t missing. Run: rustup target add aarch64-linux-android x86_64-linux-android"
    $failed = $true
  }
}

# Tauri auto-detects a LAN IP and often picks Clash/TUN 198.18.0.0/15, which the
# emulator cannot reach (white WebView). 10.0.2.2 is the emulator loopback alias.
if (-not $env:TAURI_DEV_HOST) {
  $env:TAURI_DEV_HOST = "10.0.2.2"
}
Ok "TAURI_DEV_HOST=$env:TAURI_DEV_HOST"

if ($failed) {
  Write-Host ""
  Write-Host "UI shell is ready; Android project files (src-tauri/gen/android) are generated by:"
  Write-Host "  npx tauri android init --ci"
  Write-Host "  npx tauri android dev"
  Write-Host "Those commands need the SDK/NDK above. This machine currently cannot run them."
  exit 1
}

Ok "Android toolchain looks ready."

if ($Passthru -and $Passthru.Count -gt 0) {
  $cmd = $Passthru[0]
  $cmdArgs = @()
  if ($Passthru.Count -gt 1) {
    $cmdArgs = $Passthru[1..($Passthru.Count - 1)]
  }

  $joined = ($cmdArgs -join " ")
  if ($joined -match "android dev") {
    if ($joined -notmatch "--host") {
      $cmdArgs += @("--host", $env:TAURI_DEV_HOST)
    }
    if ($env:TAURI_DEV_HOST -eq "10.0.2.2" -and $joined -notmatch "no-dev-server-wait") {
      # Host OS cannot TCP to 10.0.2.2 (emulator-only alias); skip CLI health-check.
      $cmdArgs += "--no-dev-server-wait"
    }
    # Multiple adb devices makes the CLI prompt; emulator host only works on AVDs.
    if ($env:TAURI_DEV_HOST -eq "10.0.2.2" -and $joined -notmatch "Pixel_|emulator-") {
      $adb = Join-Path $sdk "platform-tools\adb.exe"
      if (Test-Path $adb) {
        $avd = (& $adb emu avd name 2>$null | Select-Object -First 1)
        if ($avd) { $avd = $avd.Trim() }
        if ($avd -and $avd -ne "OK") {
          $cmdArgs += $avd
          Ok "Android device=$avd"
        }
      }
    }
  }

  & $cmd @cmdArgs
  exit $LASTEXITCODE
}

exit 0
